### ISSUE TITLE
Dependencies for this library?

### ISSUE THREAD

**Issue by vstath** [pyericz/promise-lua#2]
Hello,

are there any dependencies of this library or the examples? If so, what are they?

**Comment by pyericz** [comment]
No, there are no dependencies for `promise-lua`. The mentioned function `setTimeout` is an example of async methods, which can be implemented by yourself. For quick testing, you may also take a look at [luvit's setTimeout](https://luvit.io/api/timer.html#timer_timer_settimeout_delay_callback).
